const express = require('express');
const router = express.Router();
const proportionController = require('../controllers/proportionController');
router.get('/', proportionController.showProportionList);
router.get('/add', proportionController.showAddProportionForm);
router.get('/details/:propId?', proportionController.showProportionDetails);
router.get('/edit/:propId?', proportionController.showEditProportionForm);
router.post('/add', proportionController.addProportion);
router.post('/edit', proportionController.updateProportion);
router.get('/delete/:propId', proportionController.deleteProportion);
module.exports = router;